version: '2'
services:
  web:
    image: milvusbootcamp/pic-search-webclient:0.1.0
    ports:
      - 8001:80
    networks:
      - front-tier
      - back-tier

  milvus:
    image: milvusdb/milvus:0.7.0-cpu-d031120-de409b
    links:
      - web
    networks:
      - back-tier

  lb:
    image: milvusbootcamp/pic-search-webserver:0.3.0 
    links:
      - web
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge